### ISSUE TITLE
表格自适应高度以及表格搜索条件展开折叠功能

### ISSUE THREAD

**Issue by yanbowe** [pearadmin/pear-admin-naive#1]
作者这两个功能是否考虑增加呢？

**Comment by JobinJia** [comment]
嗯啊，会的，常用及常见的都会增加进去。只是人手不够，所以进度会慢++

**Comment by JobinJia** [comment]
> 作者这两个功能是否考虑增加呢？

忘了说了，欢迎PR ( 逃

**Comment by JobinJia** [comment]
表格搜索条件展开折叠已增加，表格自适应高度暂时待定。因为表格默认开启虚拟滚动，需要一个固定高度。
但在Table Toolbar中有提表格高度的工具。可以使用这个调整

**Comment by yanbowe** [comment]
> 表格搜索条件展开折叠已增加，表格自适应高度暂时待定。因为表格默认开启虚拟滚动，需要一个固定高度。 但在Table Toolbar中有提表格高度的工具。可以使用这个调整

好的，感谢大佬
